project:
  type: website

website:
  title: "gregers kjerulf dubrow"
  description: "personal website for gregers kjerulf dubrow"
  site-url: https://www.gregdubrow.io
  cookie-consent:
    type: express
  google-analytics:
    tracking-id: "G-09CSH6M61C"
    anonymize-ip: false
  repo-url: https://github.com/greg-dubrow/greg_dubrow_io
  open-graph: true
  navbar:
    pinned: true
    right:
      - text: "About me"
        file: about.qmd
      - text: "Consulting"
        file: consulting.qmd
      - icon: github
        href: https://github.com/greg-dubrow
      - icon: linkedin
        href: https://linkedin.com/in/dubrowg/
      - icon: bluesky
        href: https://bsky.app/profile/gregerskjerulf.bsky.social
      - icon: rss
        href: index.xml
  page-footer:
    left:
      - href: https://www.quarto.org
        text: Built with Quarto
    right:
      - href: license.qmd
        text: License
format:
  html:
    theme: cosmo
    css: styles.css
    code-overflow: scroll
    link-external-newwindow: true
editor:
  mode: source

