project:
  type: website

website:
  title: "gregers kjerulf dubrow"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/greg-dubrow
      - icon: linkedin
        href: https://linkedin.com/in/dubrowg/
      - icon: twitter
        href: https://twitter.com/greg_dubrow
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

